### ISSUE TITLE
Any plan to support to GitLab?

### ISSUE THREAD

**Issue by k010c1232** [xgeek-net/pipeline#10]
Do you have a plan to support to GitLab?

**Comment by xgeek-net** [comment]
Thanks for your feedback. This feature depends on how many developers want, like support for local Git, recently I'm focusing on ChangeSet for SFDC to SFDC, which is used more, specially in Japan.

**Comment by xgeek-net** [comment]
Hi, @k010c1232 
Just released a new version v2.0.0 that supports GitLab git connection, hope it will be helpful for you.
https://github.com/xgeek-net/pipeline/releases/tag/2.0.0

Feel free to reopen this issue if you have any question.
