### ISSUE TITLE
本番への適用について

### ISSUE THREAD

**Issue by hidehito-matsuyama-uhuru** [xgeek-net/pipeline#13]
本番へのリリース時に、検証のステップのみを実施したい場合があるので、検証機能の実装を検討いただきたく。

**Comment by xgeek-net** [comment]
@hidehito-matsuyama-uhuru 
ご意見ありがとうございます。直近で対応する予定です。

**Comment by xgeek-net** [comment]
@hidehito-matsuyama-uhuru 
お待たせしました、検証機能を追加しました、最新版(v2.0.0版)をご利用ください。
https://github.com/xgeek-net/pipeline/releases/tag/2.0.0

BTW, それ以外にBacklog Gitの対応も最新版に追加されています。
問題なければ本Issueのクローズをお願いします。
