### ISSUE TITLE
「承認プロセス」の対応

### ISSUE THREAD

**Issue by daiki-sasakura-uhuru** [xgeek-net/pipeline#14]
承認プロセスが一覧表示されません。実装を検討ください。

**Comment by xgeek-net** [comment]
@daiki-sasakura-uhuru 
起票ありがとうございます。そうですね、直近で対応する予定です。

**Comment by xgeek-net** [comment]
@daiki-sasakura-uhuru 
お待たせしました、承認プロセス取得問題を対応しました、最新版(v2.0.0版)をご利用ください。
https://github.com/xgeek-net/pipeline/releases/tag/2.0.0

**Comment by daiki-sasakura-uhuru** [comment]
ありがとうございます。
リスト確認ができました。
