### ISSUE TITLE
run pipeline is error

### ISSUE THREAD

**Issue by tran-binh-mulodo** [xgeek-net/pipeline#18]
Hi Admin,
I have setting as image below:
![pipeline](https://user-images.githubusercontent.com/31844916/59813507-f4261200-933b-11e9-8f90-13f90c9e58ec.png)
But, when run pipeline then display message error as below:
09:12:41 [SF.api] Authorize : true
09:12:41 [SFDC] Retrieve from Org Personal:
09:12:41         > ApexPage [TestPipeline]
09:12:43 [SFDC] Retrieve metadata Done.
09:12:43 [ERROR] Run pipeline : Error: EEXIST: file already exists, mkdir 'C:\Users\admin\AppData\Roaming\pipeline\pipeline\ded35642-df1f-409a-a33d-5315d6925b3c\src.zip'

You can help me with issue this. thanks!

**Comment by xgeek-net** [comment]
Hi, @tran-binh-mulodo , seems it is a bug in Destruct deploy, will fix it. 
Thank you for your report!

**Comment by xgeek-net** [comment]
@tran-binh-mulodo , just fixed this bug in latest version [(2.0.1)](https://github.com/xgeek-net/pipeline/releases/tag/2.0.1) , get update and try again.
Please feel free to reopen this issue if it is still not working.

**Comment by tran-binh-mulodo** [comment]
many thanks for your support. I will get and check on new version.
