### ISSUE TITLE
Add "Change Test Level Feature"

### ISSUE THREAD

**Issue by hubwozniak** [xgeek-net/pipeline#7]
Hi!
It would be great if there is possibility to chose between Run All/Local/Specific and no Test ;)

**Comment by xgeek-net** [comment]
Hi, @hubwozniak 
Thanks for your reporting, `Run All/Local` will be added in next version as a select list, is Specific option really necessary? (At least me) I've never used it until now.

**Comment by xgeek-net** [comment]
Hi, `Run All Text` feature is released at [latest version](https://github.com/xgeek-net/pipeline/releases) , get update and try again. 
Plz feel free to reopen this issue if you have any question.
